version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING_DEFAULT}
    networks:
      - deploy-guide-dev

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - deploy-guide-dev
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  deploy-guide-dev:
    driver: bridge

volumes:
  pgdata:
