version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=main;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - back

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - back
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  back:
    driver: bridge

volumes:
  pgdata:
